## Pandas - python

#### What is pandas? 

Pandas is open source library that is widely used for data science and analysis. It is built on top of NumPy, which provides support for multi-dimentional arrays.

Pandas is one of the most popular data wrangling packages.

#### What can we do with pandas?

1. Data Cleaning
2. Data fill
3. Data Normalization
4. Merges and joins
5. Data Inspection
6. Loading and saving data

#### What is data frames?

Dataframes is 2D labeled data structure with columns which can have different data types. We can think of dataframes as spreadsheet or SQL tables or dict of series objects.

## Creating DataFrames and Basic Functions on it

In [1]:
# Importing pandas

import pandas as pd
import numpy as np

In [4]:
# Creating dataframes

arr = np.arange(0,50).reshape(5,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [6]:
df = pd.DataFrame(arr, index=['row1', 'row2', 'row3', 'row4', 'row5'], 
                  columns=['col1', 'col2', 'col3', 'col4', 'col5', 'col6', 'col7', 'col8', 'col9', 'col10'])
df

col1  col2  col3  col4  col5  col6  col7  col8  col9  col10
row1     0     1     2     3     4     5     6     7     8      9
row2    10    11    12    13    14    15    16    17    18     19
row3    20    21    22    23    24    25    26    27    28     29
row4    30    31    32    33    34    35    36    37    38     39
row5    40    41    42    43    44    45    46    47    48     49

## How to access the dataframe? - Indexing & Types

In [9]:
# loc for row indexing

df.loc['row1'] 

col1     0
col2     1
col3     2
col4     3
col5     4
col6     5
col7     6
col8     7
col9     8
col10    9
Name: row1, dtype: int32

In [11]:
type(df.loc['row1'] )

pandas.core.series.Series

#### Note: type is series

series can be any one row or one column

In [14]:
# iloc = index location

df.iloc[:,:] # row indexes, column indexes

col1  col2  col3  col4  col5  col6  col7  col8  col9  col10
row1     0     1     2     3     4     5     6     7     8      9
row2    10    11    12    13    14    15    16    17    18     19
row3    20    21    22    23    24    25    26    27    28     29
row4    30    31    32    33    34    35    36    37    38     39
row5    40    41    42    43    44    45    46    47    48     49

In [15]:
df.iloc[0:2,0:2]

col1  col2
row1     0     1
row2    10    11

In [16]:
# Note the type

type(df.iloc[0:2,0:2])

pandas.core.frame.DataFrame

In [17]:
df.iloc[0:3,0:1]

col1
row1     0
row2    10
row3    20

In [18]:
# Note the type - Dataframe [Important]
type(df.iloc[0:3,0:1])

pandas.core.frame.DataFrame

In [19]:
df.iloc[0:3, 0]

row1     0
row2    10
row3    20
Name: col1, dtype: int32

In [20]:
# Note the type - series
type(df.iloc[0:3, 0])

pandas.core.series.Series

In [21]:
df.iloc[:,3:]

col4  col5  col6  col7  col8  col9  col10
row1     3     4     5     6     7     8      9
row2    13    14    15    16    17    18     19
row3    23    24    25    26    27    28     29
row4    33    34    35    36    37    38     39
row5    43    44    45    46    47    48     49

In [22]:
# Getting only the values in the dataframe OR Converting dataframe into array 

df.iloc[:,3:].values

array([[ 3,  4,  5,  6,  7,  8,  9],
       [13, 14, 15, 16, 17, 18, 19],
       [23, 24, 25, 26, 27, 28, 29],
       [33, 34, 35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47, 48, 49]])

In [25]:
df['col1'] # This will be a series

row1     0
row2    10
row3    20
row4    30
row5    40
Name: col1, dtype: int32

In [26]:
type(df['col1'])

pandas.core.series.Series

In [38]:
df[['col1', 'col2']]

col1  col2
row1     0     1
row2    10    11
row3    20    21
row4    30    31
row5    40    41

### Checking the null values

In [27]:
df.isnull().sum()

col1     0
col2     0
col3     0
col4     0
col5     0
col6     0
col7     0
col8     0
col9     0
col10    0
dtype: int64

### Counting value counts - will not count one element twice


In [28]:
df['col1'].value_counts()

0     1
10    1
20    1
30    1
40    1
Name: col1, dtype: int64

### Getting unique values/elements from a series

In [29]:
df['col2'].unique()

array([ 1, 11, 21, 31, 41])

In [32]:
df2 = pd.DataFrame([1,2,2,2,3,4,4,4,3,4,5,7], columns=['col1'])
df2

col1
0      1
1      2
2      2
3      2
4      3
5      4
6      4
7      4
8      3
9      4
10     5
11     7

In [33]:
df2['col1'].unique()

array([1, 2, 3, 4, 5, 7], dtype=int64)

In [34]:
df2['col1'].value_counts()

4    4
2    3
3    2
1    1
5    1
7    1
Name: col1, dtype: int64

In [35]:
df.head()

col1  col2  col3  col4  col5  col6  col7  col8  col9  col10
row1     0     1     2     3     4     5     6     7     8      9
row2    10    11    12    13    14    15    16    17    18     19
row3    20    21    22    23    24    25    26    27    28     29
row4    30    31    32    33    34    35    36    37    38     39
row5    40    41    42    43    44    45    46    47    48     49

In [36]:
df.tail(3) # Last 3 rows

col1  col2  col3  col4  col5  col6  col7  col8  col9  col10
row3    20    21    22    23    24    25    26    27    28     29
row4    30    31    32    33    34    35    36    37    38     39
row5    40    41    42    43    44    45    46    47    48     49

## Reading different file formats and parameters

In [4]:
df = pd.read_csv("tallest_buildings_global.csv") 
# CSV ---> Comma Seperated Values


In [3]:
df.head()

rank                                  name  height_m  height_ft  \
0     1                          Burj Khalifa     828.0       2717   
1     2                           Merdeka 118     678.9       2227   
2     3                        Shanghai Tower     632.0       2073   
3     4             Abraj Al-Bait Clock Tower     601.0       1972   
4     5  Ping An International Finance Centre     599.1       1966   

   year_built  floors_above  floors_below_ground          city  \
0        2010           163                  1.0         Dubai   
1        2022           118                  5.0  Kuala Lumpur   
2        2015           128                  5.0      Shanghai   
3        2012           120                  3.0         Mecca   
4        2017           115                  5.0      Shenzhen   

                country  
0  United Arab Emirates  
1              Malaysia  
2                 China  
3          Saudi Arabia  
4                 China

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   rank                 78 non-null     int64  
 1   name                 78 non-null     object 
 2   height_m             78 non-null     float64
 3   height_ft            78 non-null     int64  
 4   year_built           78 non-null     int64  
 5   floors_above         78 non-null     int64  
 6   floors_below_ground  67 non-null     float64
 7   city                 78 non-null     object 
 8   country              78 non-null     object 
dtypes: float64(2), int64(4), object(3)
memory usage: 5.6+ KB


In [6]:
df.describe() # Only for numeric values

rank    height_m    height_ft   year_built  floors_above  \
count  78.000000   78.000000    78.000000    78.000000     78.000000   
mean   39.500000  427.306410  1401.923077  2012.384615     87.705128   
std    22.660538   84.193166   276.241038    12.808511     17.793264   
min     1.000000  350.000000  1148.000000  1931.000000     54.000000   
25%    20.250000  370.050000  1214.250000  2010.250000     75.500000   
50%    39.500000  401.850000  1318.500000  2016.500000     86.500000   
75%    58.750000  451.425000  1481.250000  2019.000000     97.750000   
max    78.000000  828.000000  2717.000000  2022.000000    163.000000   

       floors_below_ground  
count            67.000000  
mean              4.000000  
std               1.381699  
min               1.000000  
25%               3.000000  
50%               4.000000  
75%               5.000000  
max               8.000000

In [7]:
# Reading ; seperated values file say test.csv

# test_df = pd.read_csv("test.csv", sep=';')

### Applying some in-built fuctions

In [8]:
df['floors_below_ground'].value_counts()

3.0    18
5.0    17
4.0    16
6.0     6
2.0     6
1.0     2
8.0     1
7.0     1
Name: floors_below_ground, dtype: int64

## CSV 

In [12]:
from io import StringIO, BytesIO

In [10]:
# Structure of a CSV file 

data = ('col1, col2, col3\n'
       'x, y, 1\n'
       'a, b, 2\n'
       'c, d, 3')
type(data)

str

In [11]:
# StringIO() ---> Text I/O implementation using an in-memory buffer.

pd.read_csv(StringIO(data))

col1  col2   col3
0    x     y      1
1    a     b      2
2    c     d      3

In [21]:
# Read only some specific columns using usecols parameter

data1 = ('col1,col2,col3\n'
       'x,y,1\n'
       'a,b,2\n'
       'c,d,3')

# data1 should be only comma seperated without space unline data

df2 = pd.read_csv(StringIO(data1), usecols=['col1', 'col2'], sep=',')

In [22]:
df2

col1 col2
0    x    y
1    a    b
2    c    d

In [24]:
# Specifying datatypes of columns

df3 = pd.read_csv(StringIO(data1), dtype=object)

df3['col3'][0]

'1'

As we can see that 1 is object and not integer

In [26]:
# Making integer

data2 = ('col1,col2,col3\n'
       '3,2,1\n'
       '4,1,2\n'
       '5,6,3')


df4 = pd.read_csv(StringIO(data2), dtype=int)

df4['col3'][0]

1

In [27]:
df4

col1  col2  col3
0     3     2     1
1     4     1     2
2     5     6     3

In [28]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    3 non-null      int32
 1   col2    3 non-null      int32
 2   col3    3 non-null      int32
dtypes: int32(3)
memory usage: 164.0 bytes


As we can see all the columns are int32

In [30]:
df5 = pd.read_csv(StringIO(data2), dtype={'col1':int, 'col2':float, 'col3':'Int64'})
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   col1    3 non-null      int32  
 1   col2    3 non-null      float64
 2   col3    3 non-null      Int64  
dtypes: Int64(1), float64(1), int32(1)
memory usage: 191.0 bytes


In [31]:
df5.dtypes

col1      int32
col2    float64
col3      Int64
dtype: object

In [32]:
# index column with index_col parameter

data2 = ('index,col1,col2,col3\n'
       '1,3,2,1\n'
       '2,4,1,2\n'
       '3,5,6,3')

df = pd.read_csv(StringIO(data2))
df

index  col1  col2  col3
0      1     3     2     1
1      2     4     1     2
2      3     5     6     3

As we can see that index column is not taken as index. To fix that we use index_col

In [33]:
df = pd.read_csv(StringIO(data2), index_col=0)
df

col1  col2  col3
index                  
1         3     2     1
2         4     1     2
3         5     6     3

In [37]:
# Another case while reading data, if numbers in below data are taken 
# as indexes and the last column becomes NAN due to that then follow the 
# below code using index_col=False

data2 = ('a,b,c\n'
       '3,apple,mango\n'
       '4,parrot,bat\n'
       '5,man,woman')

df = pd.read_csv(StringIO(data2), index_col=False)
df

a       b      c
0  3   apple  mango
1  4  parrot    bat
2  5     man  woman

In [41]:
# Combining use_col and index_col

data2 = ('a,b,c\n'
       '3,apple,mango\n'
       '4,parrot,bat\n'
       '5,man,woman')

df = pd.read_csv(StringIO(data2),usecols=['b', 'c'],index_col=False)
df


b      c
0   apple  mango
1  parrot    bat
2     man  woman

In [42]:
# Quoting and escaping characters ---> Uesd a lot in NLP

data = ('a,b\n"hello \\"Bob\\", nice to see you",5')

type(data)

str

In [43]:
pd.read_csv(StringIO(data), escapechar='\\')

# a ---> hello \\"Bob\\", nice to see you
# b ---> 5

a  b
0  hello "Bob", nice to see you  5

In [ ]:
# Reading tab seperated files where tab ---> '\t'

# df = pd.read_csv(path_of_file, sep='\t')

## JSON 

In [48]:
# key:value pairs
# Following we have some nested JSON data

Data = '{"name":"James", "email":"jammy@someail.co.in", "experience": [{"title1": "Team Lead", "title2": "Developer"}]}'
Df = pd.read_json(Data)

If we have nested JSON will not be exactly converted to columns

In [45]:
# iris dataset in JSON format link. You can check by visiting the link below

iris_json = pd.read_json('https://storage.googleapis.com/kagglesdsdata/datasets/20079/26025/iris.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20211211%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20211211T130655Z&X-Goog-Expires=259199&X-Goog-SignedHeaders=host&X-Goog-Signature=7c8e5062d0f4f269e1b4856001c7a9e62700985c07fee13ac14712c0564737f3297a3d753f11e9977b79341b5f327fcd568f7c9727a1533c09b6f51c523c291516ff23a853d20b549e778b7c82510ebb739b82acaf07641f198f92eb72f2585ec3d1c986f95bd44b5ef965a27c342b63e4f1971ece21606e25783bf37592e8709049a281ccc97b6896eaa59d11d8bb9ea158d2ec510b5cb311ce93ba998fff4caae28cc4c81eb6e98f8d516eb468e8ea9af91d7153db3a48502f59a54481f02348cfde5aaceab7b419cd5f1fe8baee32f3e0cee1e6a248613439ae34c79f094560eaf8429dbb8915a20e4559c8a012e8ccb82f0824729d32fbfa5284c57090b3')

In [46]:
iris_json.head()

sepalLength  sepalWidth  petalLength  petalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa

In [47]:
# Convert json data to csv

iris_json.to_csv('iris_data.csv')

In [50]:
Df

name                email                                      experience
0  James  jammy@someail.co.in  {'title1': 'Team Lead', 'title2': 'Developer'}

In [49]:
# convert json to different json formats
# Convert the object to a JSON string.

Df.to_json()

'{"name":{"0":"James"},"email":{"0":"jammy@someail.co.in"},"experience":{"0":{"title1":"Team Lead","title2":"Developer"}}}'

To avoid making the key value pair for each column we can use parameter orient='records'

In [51]:
Df.to_json(orient='records') # will be converted to json record by record

'[{"name":"James","email":"jammy@someail.co.in","experience":{"title1":"Team Lead","title2":"Developer"}}]'

## HTML Tables

##### Note:
read_html returns a list of DataFrame objects, even if there is only a single table contained in the HTML content

Refer to [docs](https://pandas.pydata.org/pandas-docs/version/0.17.1/io.html#io-read-html) for more info. 

In [9]:
# Reading tables from HTML

url = 'https://en.wikipedia.org/wiki/Mobile_country_code'

# match parameter:
# str or compiled regular expression, optional
# The set of tables containing text matching this regex or string will be
# returned. Unless the HTML is extremely simple you will probably need to
# pass a non-empty string here.

dfs = pd.read_html(url, match='Country', header=0) 

dfs[0]

Mobile country code                                    Country ISO 3166  \
0                    289                                 A Abkhazia    GE-AB   
1                    412                                Afghanistan       AF   
2                    276                                    Albania       AL   
3                    603                                    Algeria       DZ   
4                    544  American Samoa (United States of America)       AS   
..                   ...                                        ...      ...   
247                  452                                    Vietnam       VN   
248                  543                        W Wallis and Futuna       WF   
249                  421                                    Y Yemen       YE   
250                  645                                   Z Zambia       ZM   
251                  648                                   Zimbabwe       ZW   

                                  Mobile network codes National MNC authority  \
0             List of mobile network codes in Abkhazia                    NaN   
1          List of mobile network codes in Afghanistan                    NaN   
2              List of mobile network codes in Albania                    NaN   
3              List of mobile network codes in Algeria                    NaN   
4       List of mobile network codes in American Samoa                    NaN   
..                                                 ...                    ...   
247        List of mobile network codes in the Vietnam                    NaN   
248  List of mobile network codes in Wallis and Futuna                    NaN   
249          List of mobile network codes in the Yemen                    NaN   
250             List of mobile network codes in Zambia                    NaN   
251           List of mobile network codes in Zimbabwe                    NaN   

                      Remarks  
0    MCC is not listed by ITU  
1                         NaN  
2                         NaN  
3                         NaN  
4                         NaN  
..                        ...  
247                       NaN  
248                       NaN  
249                       NaN  
250                       NaN  
251                       NaN  

[252 rows x 6 columns]

## Excel files

In [10]:
df_excel = pd.read_excel('Processed_Customer_Analytics.xlsx')
df_excel.head()

Unnamed: 0   DATE  STORE_NBR  LYLTY_CARD_NBR  TXN_ID  PROD_NBR  \
0           0  43390          1            1000       1         5   
1           1  43599          1            1307     348        66   
2           2  43605          1            1343     383        61   
3           3  43329          2            2373     974        69   
4           4  43330          2            2426    1038       108   

                                  PROD_NAME  PROD_QTY  TOT_SALES  PACK_SIZE  \
0    Natural Chip        Compny SeaSalt175g         2        6.0        175   
1                  CCs Nacho Cheese    175g         3        6.3        175   
2    Smiths Crinkle Cut  Chips Chicken 170g         2        2.9        170   
3    Smiths Chip Thinly  S/Cream&Onion 175g         5       15.0        175   
4  Kettle Tortilla ChpsHny&Jlpno Chili 150g         3       13.8        150   

                               BRD_NAME  
0    Natural Chip        Compny SeaSalt  
1                  CCs Nacho Cheese      
2    Smiths Crinkle Cut  Chips Chicken   
3    Smiths Chip Thinly  S/Cream&Onion   
4  Kettle Tortilla ChpsHny&Jlpno Chili

There is also a parameter sheet_name in read_excel to provide the info regarding which sheet we wnat to read. By default, it is set to zero. 

You can read about it by pressing shift+tab

## Pickling

All pandas objects are equipped with to_pickle method which use Python's cPickle module to save the data structures to disk using the pickle format.

Pickle can be used to serialize Python object structures, which refers to the process of converting an object in the memory to a byte stream that can be stored as a binary file on disk. 

When we load it back to a Python program, this binary file can be de-serialized back to a Python object.

In [13]:
data2 = ('a,b,c\n'
       '3,apple,mango\n'
       '4,parrot,bat\n'
       '5,man,woman')

df = pd.read_csv(StringIO(data2))
df


a       b      c
0  3   apple  mango
1  4  parrot    bat
2  5     man  woman

In [14]:
# Converting above dataframe to pickle

df.to_pickle('df_pickle_file')

In [15]:
# Reading pickle file

pd.read_pickle('df_pickle_file')

a       b      c
0  3   apple  mango
1  4  parrot    bat
2  5     man  woman